name: Gitee Sync
run-name: "ğŸ­ğŸ”ƒâ™¾ï¸[${{ github.workflow }}] - ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow}}
  cancel-in-progress: true

jobs:
  sync_to_gitee:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2

      - name: sync-gitee-mirror
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: copdips/copdips.github.io
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PAT }}
